Repository mjennings061/viking-log-keeper, pull requests merged in 2024-08, with the labels that each got.

#69 New template
  docs/2965D_YYMMDD_ZEXXX.xltx
Labels: documentation, enhancement

#70 45 update 2965d template
  docs/2965D_YYMMDD_ZEXXX.xltx
Labels: documentation, enhancement

#74 Template with bug fixes for formulas and data validation
  docs/2965D_YYMMDD_ZEXXX.xltx
Labels: bug, documentation

#77 Organise imports - Streamlit did not like that
  src/dashboard/main.py
Labels: bug

#78 Upload log sheets to the dashboard directly
  requirements.txt
  setup.py
  src/dashboard/main.py
  src/dashboard/utils.py
  src/log_keeper/output.py
  tests/test_dashboard.py
Labels: enhancement

#80 Database rework - major breaking changes
  .github/workflows/python-package.yml
  README.md
  docs/dashboard.png
  docs/login.png
  requirements.txt
  src/dashboard/main.py
  src/dashboard/utils.py
  src/log_keeper/get_config.py
  src/log_keeper/output.py
  tests/test_dashboard.py
Labels: documentation, enhancement

#82 Catch empty username or password; Minor layout changes
  src/dashboard/__init__.py
  src/dashboard/main.py
  src/dashboard/plots.py
  src/dashboard/utils.py
  src/log_keeper/__init__.py
  src/log_keeper/get_config.py
  src/log_keeper/output.py
Labels: bug

#84 66 add total launches per day
  setup.py
  src/dashboard/main.py
  src/dashboard/plots.py
  src/dashboard/utils.py
  src/log_keeper/get_config.py
Labels: enhancement

#86 Fixed template
  docs/2965D_YYMMDD_ZEXXX.xltx
Labels: bug
